### ISSUE TITLE
Documentation TODO list

### ISSUE THREAD

**Issue by szhorvat** [szhorvat/MaTeX#11]
This is just a personal todo list to help me keep track of documentation tasks

- [x] Add example with `epsdice`, to show how to quickly get symbols unavailable in Mathematica

- [x] Write tutorial page that explains how to prepare figures to size (suggested by C.E.)

- [x] [Improve discoverability](https://chat.stackexchange.com/transcript/message/36467276#36467276)

- [x] MaTeX Guide should have directly listed Tutorial links at the bottom.
